name = "Create Adventures"
author = "Cristhian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4aa443960143bfdccaa96fcc474e894a2c6e189f82913fb5a26a21aa2b0e7763"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"

[options]
datapack-folder = "config/paxi/datapacks"
