name = "Create Adventures"
author = "Cristhian-de-Jesus-Almeida"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3837753af1a9b83f04dd3ce71c57a15f2ef67eb4fd114ed6cd80ba69046ea346"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
datapack-folder = "global_packs/required_data"
