name = "Create Adventures"
author = "Cristhian"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c9d5d63484ada2eaa3f61d36da7d7676c0c6cdd521c32417a0424671f18290d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.229"

[options]
datapack-folder = "config/paxi/datapacks"
