// Create wrench block 
ServerEvents.tags('block', event => { 
    const wrenchableBlocks = [ 
        'minecraft:barrel', 
        'minecraft:chest', 
        'minecraft:ender_chest', 
        'minecraft:trapped_chest', 
        'minecraft:dispenser', 
        'minecraft:dropper', 
        'minecraft:crafter', 
        'minecraft:waxed_copper_bulb', 
        'minecraft:waxed_exposed_copper_bulb', 
        'minecraft:waxed_weathered_copper_bulb', 
        'minecraft:waxed_oxidized_copper_bulb', 
        'minecraft:copper_bulb', 
        'minecraft:exposed_copper_bulb', 
        'minecraft:weathered_copper_bulb', 
        'minecraft:oxidized_copper_bulb', 
        'minecraft:hopper', 
        'minecraft:cauldron', 
        'ars_additions:ender_source_jar', 
        'ars_nouveau:archwood_chest', 
        'ars_nouveau:spell_turret', 
        'ars_nouveau:volcanic_sourcelink', 
        'ars_nouveau:relay_deposit', 
        'ars_nouveau:relay_warp', 
        'ars_nouveau:basic_spell_turret', 
        'ars_nouveau:timer_spell_turret', 
        'ars_nouveau:relay_collector', 
        'ars_nouveau:rotating_spell_turret', 
        'starbunclemania:source_condenser', 
        'starbunclemania:fluid_sourcelink', 
        'starbunclemania:fluid_jar', 
        'ars_nouveau:agronomic_sourcelink', 
        'ars_nouveau:source_jar', 
        'ars_nouveau:relay', 
        'ars_nouveau:imbuement_chamber', 
        'ars_nouveau:magelight_torch', 
        'ars_nouveau:ritual_brazier', 
        'ars_nouveau:item_detector', 
        'ars_nouveau:redstone_relay', 
        'ars_nouveau:mob_jar', 
        'ars_nouveau:repository', 
        'ars_nouveau:sconce', 
        'ars_nouveau:sourcestone_sconce', 
        'ars_nouveau:polished_sconce', 
        'ars_nouveau:archwood_sconce', 
        'ars_nouveau:relay_splitter', 
        'supplementaries:relayer', 
        'minecraft:composter', 
        'minecraft:sea_lantern', 
        'supplementaries:cog_block', 
        'createages:andesite_machine', 
        'createages:copper_machine',  
        'createages:brass_machine', 
        'ars_additions:sourcestone_chain', // Duplicata removida daqui
        'ars_additions:polished_sourcestone_chain', 
        'ars_additions:golden_chain', 
        'createdeco:andesite_bars_overlay', 
        'createdeco:andesite_bars', 
        'createdeco:brass_bars_overlay', 
        'createdeco:brass_bars', 
        'createdeco:iron_bars_overlay', 
        'createdeco:copper_bars_overlay', 
        'createdeco:copper_bars', 
        'createdeco:industrial_iron_bars_overlay', 
        'createdeco:industrial_iron_bars', 
        'createdeco:industrial_iron_support', 
        'createdeco:zinc_support', 
        'createdeco:andesite_sheet_metal', 
        'createdeco:brass_sheet_metal', 
        'createdeco:iron_sheet_metal', 
        'createdeco:copper_sheet_metal', 
        'createdeco:industrial_iron_sheet_metal', 
        'createdeco:zinc_sheet_metal', 
        'createdeco:brass_hull', 
        'createdeco:iron_hull', 
        'createdeco:copper_hull', 
        'createdeco:industrial_iron_hull', 
        'createdeco:zinc_hull', 
        'createdeco:andesite_support', 
        'createdeco:brass_support', 
        'createdeco:iron_support', 
        'createdeco:copper_support', 
        'createdeco:zinc_bars_overlay', 
        'createdeco:zinc_bars', 
        'createdeco:andesite_mesh_fence', 
        'createdeco:brass_mesh_fence', 
        'createdeco:iron_mesh_fence', 
        'createdeco:copper_mesh_fence', 
        'createdeco:industrial_iron_mesh_fence', 
        'createdeco:zinc_mesh_fence', 
        'createdeco:andesite_hull', 
        'enderstorage:ender_tank' 
    ] 
    
    // Adiciona a lista estática de blocos
    event.add('create:wrench_pickup', wrenchableBlocks); 

    // Coleta TODOS os alçapões do jogo via Regex
    event.add('create:wrench_pickup', /.*:.*_trapdoor$/); 

    // Coleta TODOS os blocos vindos do mod 'dndecor' (Substituindo o antigo @dndecor)
    event.add('create:wrench_pickup', /^dndecor:.*/);

    // Adiciona uma tag de bloco inteira corretamente (Correntes do formato Common/c)
    event.add('create:wrench_pickup', '#c:chains');
});
